# Increase sub font size (set to [Alt] + [k])
ALT+k add sub-font-size +1
# Decrease sub font size (set to [Alt] + [j])
ALT+j add sub-font-size -1 
# Increase playback speed
c add speed 0.2
# Decrease playback speed
x add speed -0.2
# Increase volume
UP add volume 5
# Decrease volume
DOWN add volume -5
